# Generated by Django 6.0.7 on 2026-08-20 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('redirect_url', models.URLField(max_length=500)),
                ('rate_limit_enabled', models.BooleanField(default=True)),
                ('rate_limit_max_requests', models.PositiveIntegerField(default=80)),
                ('rate_limit_window_seconds', models.PositiveIntegerField(default=60)),
                ('total_request_limit_enabled', models.BooleanField(default=True)),
                ('total_request_limit_max', models.PositiveIntegerField(default=500)),
                ('login_attempt_max', models.PositiveIntegerField(default=2)),
                ('login_splash_delay_ms', models.PositiveIntegerField(default=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'blacklist policy',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('path', models.TextField(blank=True, default='')),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('device', models.CharField(blank=True, default='', max_length=32)),
                ('os', models.CharField(blank=True, default='', max_length=128)),
                ('browser', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('query', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('kind', models.CharField(choices=[('manual', 'manual'), ('rate', 'rate'), ('login', 'login'), ('limit', 'limit')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('ip', 'kind'), name='uniq_blacklist_ip_kind')],
            },
        ),
    ]
