# Generated by Django 6.0.7 on 2026-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistpolicy',
            name='login_loading_delay_ms',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
