# Generated by Django 6.0.7 on 2026-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blacklistpolicy_login_loading_delay_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistpolicy',
            name='login_loading_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blacklistpolicy',
            name='login_splash_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
